### ISSUE TITLE
Error after following install instructions. What is process.env.LCC_TOKEN and what do I need to set it to?

### ISSUE THREAD

**Issue by PositiveVibe** [zahidkhawaja/langchain-chat-nextjs#1]
Got this error when trying to run this on my own machine:

>  error - TypeError: Failed to parse URL from undefined
>     at Object.fetch (node:internal/deps/undici/undici:12789:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(api)/./pages/api/chat.js:6:22)
>     at async Object.apiResolver (/Users/zbadgerm/Desktop/projects/chatGPT/langChain/langchain-chat-nextjs/node_modules/next/dist/server/api-utils/node.js:363:9)
>     at async DevServer.runApi (/Users/zbadgerm/Desktop/projects/chatGPT/langChain/langchain-chat-nextjs/node_modules/next/dist/server/next-server.js:487:9)
>     ... 4 lines matching cause stack trace ...
>     at async DevServer.handleRequest (/Users/zbadgerm/Desktop/projects/chatGPT/langChain/langchain-chat-nextjs/node_modules/next/dist/server/base-server.js:322:20) {
>   page: '/api/chat',
>   [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
>       at new NodeError (node:internal/errors:399:5)
>       at URL.onParseError (node:internal/url:565:9)
>       at new URL (node:internal/url:645:5)
>       at new Request (node:internal/deps/undici/undici:6947:25)
>       at fetch2 (node:internal/deps/undici/undici:11930:25)
>       at Object.fetch (node:internal/deps/undici/undici:12787:18)
>       at fetch (node:internal/process/pre_execution:241:25)
>       at __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(api)/./pages/api/chat.js:6:28)
>       at Object.apiResolver (/Users/zbadgerm/Desktop/projects/chatGPT/langChain/langchain-chat-nextjs/node_modules/next/dist/server/api-utils/node.js:363:15)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async DevServer.runApi (/Users/zbadgerm/Desktop/projects/chatGPT/langChain/langchain-chat-nextjs/node_modules/next/dist/server/next-server.js:487:9)
>       at async Object.fn (/Users/zbadgerm/Desktop/projects/chatGPT/langChain/langchain-chat-nextjs/node_modules/next/dist/server/next-server.js:749:37)
>       at async Router.execute (/Users/zbadgerm/Desktop/projects/chatGPT/langChain/langchain-chat-nextjs/node_modules/next/dist/server/router.js:253:36)
>       at async DevServer.run (/Users/zbadgerm/Desktop/projects/chatGPT/langChain/langchain-chat-nextjs/node_modules/next/dist/server/base-server.js:384:29)
>       at async DevServer.run (/Users/zbadgerm/Desktop/projects/chatGPT/langChain/langchain-chat-nextjs/node_modules/next/dist/server/dev/next-dev-server.js:741:20)
>       at async DevServer.handleRequest (/Users/zbadgerm/Desktop/projects/chatGPT/langChain/langchain-chat-nextjs/node_modules/next/dist/server/base-server.js:322:20) {
>     input: 'undefined',
>     code: 'ERR_INVALID_URL'
>   }
> }

Any help would be appreciated. Trying to make my own little chatbot.

**Comment by pankajsingh92533** [comment]
LCC_ENDPOINT_URL is defining the API endpoint that this function is calling to likely pass the question and history to some machine learning model or chatbot service and return the response.
